name: mimidoctor
favicon: null
layout_spectrum: 0.22387
typography_spectrum: 0.4677
title: Photographer
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#b4c1ca'
    - '#000000'
    - '#6c838b'
    - '#38402b'
    - '#942c21'
  brandStrength: 0.5595536804758012
  lightness: 0.6218005083501339
  saturation: 0.22801079461351037
  rhythmicContrast: 0.3593891174532473
purpose: []
