name: mimidoctor
favicon: null
layout_spectrum: 0.6407485869713128
typography_spectrum: 0.5420333286747336
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.5595536804758012
  lightness: 0.6218005083501339
  saturation: 0.22801079461351037
  rhythmicContrast: 0.3593891174532473
purpose: []
